export const LAY_DATA_TRANG_CHU = 'LAY_DATA_TRANG_CHU';
export const DANG_NHAP = 'DANG_NHAP';
export const DANG_XUAT = 'DANG_XUAT';
export const DANG_KY = 'DANG_KY';
export const CHI_TIET_CONG_VIEC = 'CHI_TIET_CONG_VIEC';
export const UNG_TUYEN = 'UNG_TUYEN';
export const DANG_TUYEN = 'DANG_TUYEN';
export const THEM_TIN_TUC = 'THEM_TIN_TUC';
export const LAY_DATA_TIN_TUC = 'LAY_DATA_TIN_TUC';
export const CHI_TIET_TIN_TUC = 'CHI_TIET_TIN_TUC';
export const CAP_NHAT_THONG_TIN = 'CAP_NHAT_THONG_TIN';
export const KICH_HOAT_NHA_TUYEN_DUNG = 'KICH_HOAT_NHA_TUYEN_DUNG';
export const LAY_DANH_SACH_DANG_KY_NHA_TUYEN_DUNG = 'LAY_DANH_SACH_DANG_KY_NHA_TUYEN_DUNG';
export const DUYET_NHA_TUYEN_DUNG = 'DUYET_NHA_TUYEN_DUNG';
export const LAY_THONG_TIN_TAI_KHOAN = 'LAY_THONG_TIN_TAI_KHOAN';
export const LAY_DANH_SACH_CONG_VIEC = 'LAY_DANH_SACH_CONG_VIEC';
export const LAY_DANH_SACH_CONG_VIEC_LAN_DAU = 'LAY_DANH_SACH_CONG_VIEC_LAN_DAU';
export const TIM_KIEM_CONG_VIEC = 'TIM_KIEM_CONG_VIEC';
export const TIM_KIEM_CONG_VIEC_TRANG_DANH_SACH = 'TIM_KIEM_CONG_VIEC_TRANG_DANH_SACH';
export const TIM_KIEM_CONG_VIEC_LAN_DAU_TRANG_DANH_SACH = 'TIM_KIEM_CONG_VIEC_LAN_DAU_TRANG_DANH_SACH';















