export const LAY_DATA_TRANG_CHU = 'LAY_DATA_TRANG_CHU';
export const DANG_NHAP = 'DANG_NHAP';
export const DANG_XUAT = 'DANG_XUAT';
export const DANG_KY = 'DANG_KY';
export const CHI_TIET_CONG_VIEC = 'CHI_TIET_CONG_VIEC';
export const UNG_TUYEN = 'UNG_TUYEN';
export const DANG_TUYEN = 'DANG_TUYEN';
export const THEM_TIN_TUC = 'THEM_TIN_TUC';
export const LAY_DATA_TIN_TUC = 'LAY_DATA_TIN_TUC';
export const CHI_TIET_TIN_TUC = 'CHI_TIET_TIN_TUC';
export const CAP_NHAT_THONG_TIN = 'CAP_NHAT_THONG_TIN';
export const KICH_HOAT_NHA_TUYEN_DUNG = 'KICH_HOAT_NHA_TUYEN_DUNG';
export const LAY_DANH_SACH_DANG_KY_NHA_TUYEN_DUNG = 'LAY_DANH_SACH_DANG_KY_NHA_TUYEN_DUNG';
export const DUYET_NHA_TUYEN_DUNG = 'DUYET_NHA_TUYEN_DUNG';
export const LAY_THONG_TIN_TAI_KHOAN = 'LAY_THONG_TIN_TAI_KHOAN';
export const LAY_DANH_SACH_CONG_VIEC = 'LAY_DANH_SACH_CONG_VIEC';
export const LAY_DANH_SACH_CONG_VIEC_LAN_DAU = 'LAY_DANH_SACH_CONG_VIEC_LAN_DAU';
export const TIM_KIEM_CONG_VIEC = 'TIM_KIEM_CONG_VIEC';
export const TIM_KIEM_CONG_VIEC_TRANG_DANH_SACH = 'TIM_KIEM_CONG_VIEC_TRANG_DANH_SACH';
export const TIM_KIEM_CONG_VIEC_LAN_DAU_TRANG_DANH_SACH = 'TIM_KIEM_CONG_VIEC_LAN_DAU_TRANG_DANH_SACH';
export const DANH_SACH_CONG_VIEC_DA_DANG = 'DANH_SACH_CONG_VIEC_DA_DANG';
export const DANH_SACH_CONG_VIEC_DA_NOP = 'DANH_SACH_CONG_VIEC_DA_NOP';
export const DANH_SACH_UNG_TUYEN = 'DANH_SACH_UNG_TUYEN';
export const SUA_CONG_VIEC = 'SUA_CONG_VIEC';
export const DANH_SACH_TIN_TUC_DA_DANG = 'DANH_SACH_TIN_TUC_DA_DANG';
export const XOA_TIN_TUC = 'XOA_TIN_TUC';
export const SUA_TIN_TUC = 'SUA_TIN_TUC';
export const LAY_DANH_SACH_TAI_KHOAN = 'LAY_DANH_SACH_TAI_KHOAN';
export const SUA_KHOA = 'SUA_KHOA';
export const DANH_SACH_TIN_TUC = 'DANH_SACH_TIN_TUC';
export const XOA_TIN_TUC_ADMIN = 'XOA_TIN_TUC_ADMIN';
export const LAY_DANH_SACH_CONG_VIEC_ADMIN = 'LAY_DANH_SACH_CONG_VIEC_ADMIN';
export const LAY_DANH_SACH_CONG_VIEC_LAN_DAU_ADMIN = 'LAY_DANH_SACH_CONG_VIEC_LAN_DAU_ADMIN';
export const THONG_BAO = 'THONG_BAO';
export const XEM_THONG_BAO = 'XEM_THONG_BAO';
























